## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
image:
    registry: docker.io
    repository: saikatharryc/muescheli
    tag: latest
## Kubernetes configuration
## For minikube, set this to NodePort, elsewhere use LoadBalancer
##
service:
    type: ClusterIP
    # HTTP Port
    port: 8091
    ## loadBalancerIP:
    ##
    ## nodePorts:
    ##   http: <to set explicitly, choose port between 30000-32767>
    nodePorts:
        http:
    ## Enable client source IP preservation
    ## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
    ##
    externalTrafficPolicy: Cluster
    ## Service annotations done as key:value pairs
    annotations: